
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: TwitterClone_development


test:
  <<: *default
  database: TwitterClone_test


production:
  <<: *default
  database: TwitterClone_production
  username: TwitterClone
  password: <%= ENV['TWITTERCLONE_DATABASE_PASSWORD'] %>
